# Generated by Django 3.2.7 on 2022-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
