# Generated by Django 3.2.7 on 2022-08-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_staff_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
