# Generated by Django 3.2.7 on 2022-09-02 17:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_staff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
