# Generated by Django 3.2.7 on 2022-10-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20220926_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='category',
        ),
    ]
