# Generated by Django 3.2.7 on 2022-10-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_remove_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='categories',
            field=models.ManyToManyField(to='mainsite.Category'),
        ),
    ]
